### PR TITLE
Updating all Java tests to assertTrue to assertEquals

### PR DESCRIPTION
**Pull request by nullpsi**
The current tests are a little mean, they use AssertTrue and compare two strings by looking for "contains", by default when the test fails you will get a true/false mismatch but not the strings themselves (the most helpful part to help you identify what is going wrong). As there are lots of very similar strings requested to be output as part of the tasks I had to manually update the tests while attempting the challenge to add assertEquals to help me work out what the problem was.

I feel this is a key update to assist with anyone taking the assignment and wanted to share this PR as a result :)

### CODE REVIEW

**Comment by kathrinschuler** [comment]
The problem i see with this is the leading whitespace. I think people's implementation will vary, like some will do
```
Here's a list of all videos:
  Video 1
```

and some will do
```
Here's a list of all videos:
Video 1
```

assertEquals only tests one of those (and is thus inconsistent with how we test/accept output in Python & C++)

**Comment by nullpsi** [comment]
This is fair :) Thanks for the info. One could argue that having the flexibility to format the output of the video playlists as mentioned here is less helpful than having easy to debug tests. One suggestion might be to have the questions ask for a tab character to solve this issue. However, fully accepted and happy to close the PR. Thank you for the consideration

**Comment by kathrinschuler** [comment]
Yeah you're right it's really annoying with the assertTrue :( Unfortunately I don't really know a good solution to this problem (that would also solve the same issue for the other 2 languages...

I thought maybe Regex but that would probably make it worse.

**Comment by kathrinschuler** [comment]
Hey, I am reconsidering this. In Python we check that `assert bla in out`, so the error message will be a bit better as well. Same for C++, we use `ASSERT_THAT`. Maybe we can use assertThat in Java too.

**Comment by kathrinschuler** [comment]
I created https://github.com/internship-experience-uk/google-code-sample/pull/37 to move to HamCrest assertThat, that should be a nice compromise between your suggestion and the problem we were facing (e.g. not forcing the whitespace decision on them but still give better error messages). What do you think?

**Comment by nullpsi** [comment]
Hey! If we can hover over the results when their is a failed test and see the actual text (which is looks like you can) then I think this is a big improvement on the existing assertTrue setup. If you submit the change I can verify from intellij. Thank you :)

**Comment by kathrinschuler** [comment]
Cool I'll submit mine now and close this. You can ping me in Chat as well, maybe easier :)

**Pull request closed without merging**
